# Generated by Django 6.0.1 on 2026-01-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChaiSizes',
            new_name='ChaiSize',
        ),
        migrations.RenameField(
            model_name='chaisize',
            old_name='voulme_ml',
            new_name='volume_ml',
        ),
    ]
