# Generated by Django 6.0.1 on 2026-01-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_chaisizes_chaisize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivariety',
            old_name='ingridents',
            new_name='ingredients',
        ),
    ]
