# Generated by Django 6.0 on 2025-12-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChaiVariety',
            new_name='ChaiVarieties',
        ),
    ]
