# Generated by Django 6.0 on 2025-12-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_rename_chaivariety_chaivarieties'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarieties',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chaivarieties',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
